Create best-practices.mdx
conceptadev/mix pull request #158
Opened 2024-01-16 23:02 UTC by tilucasoli

## Describe your changes
* Create a documentation for best practices
## Type of change
- **Docs** (changes to the documentation)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

2024-01-17 23:07 UTC, tilucasoli commented on website/pages/docs/guides/best-practices.mdx
> +  static const link = ButtonType._('linkButtonVariant');
Done

2024-01-17 23:11 UTC, tilucasoli commented on website/pages/docs/guides/best-practices.mdx
> +    return Pressable(
I renamed `GestureBox` to `PressureBox` as we spoke

2024-01-17 23:17 UTC, tilucasoli commented on website/pages/docs/guides/best-practices.mdx
> +  late final title = Style(
As it is a simple case, I didn't see why to use `StyleRecipe`, but I already renamed it and brought it again to Mix package.

2024-01-18 16:59 UTC, leoafarias requested changes

2024-01-18 19:06 UTC, tilucasoli commented on lib/src/utils/style_recipe.dart
> +import '../../mix.dart';
Done

2024-01-20 14:37 UTC, leoafarias approved these changes
LGTM

2024-01-20 14:38 UTC, merged